artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/nsk20/datasets/main/winequality-data.zip?raw=true
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion